### ISSUE TITLE
I want to use keystore insted of congnito login 

### ISSUE THREAD

**Issue by purvagevaria** [aws/amazon-freertos-ble-android-sdk#29]
I checked the link
https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/mobileconnectors/iot/AWSIotKeystoreHelper.html
About key store but there is no any code example how to use keystore .
I checked in another thread some one provided the links but that links are not working ,

**Comment by dan4thewin** [comment]
Hi, @purvagevaria .  I've asked one of my coworkers who's familiar with this to answer.  Please expect his response soon.

**Comment by purvagevaria** [comment]
Thanks @dan4thewin  .

**Comment by ravibhagavandas** [comment]
@purvagevaria 
For security concerns we now recommend to always use Cognito instead of creating certificates/private key for mobile apps. All of our current examples recommend using Cognito as the means to authenticate a websocket connection to AWS IoT. You can get more details on Cognito authentication from the [demo](https://github.com/aws/amazon-freertos-ble-android-sdk/blob/master/app/src/main/java/software/amazon/freertos/demo/AuthenticatorActivity.java) in this repository.

Please note the Keystore helper class and related files have been moved under aws_amplify repository [here](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotKeystoreHelper.java)

**Comment by abhidixi11** [comment]
I'm closing this issue, please feel free to open a new one.
