### ISSUE TITLE
BLE Disconnect while doing wifi Provisioning with Samsung galaxy S10 Mobile having Android 10

### ISSUE THREAD

**Issue by pentair-mywater-residentail** [aws/amazon-freertos-ble-android-sdk#30]
**Issue Description**
While Doing wifi provisioning, Ble pairing working properly, List Network is working properly, while calling Save Network with router details, it disconnect from BLE every time, we have tried on multiple s10 devices and seen the same behaviour.

**Mobile App LogCat**:
2020-08-10 13:34:57.658 20599-20693/AppID D/AmazonFreeRTOSDevice: Processing BLE command: WRITE_CHARACTERISTIC queue size: 0
2020-08-10 13:34:57.659 20599-20693/AppId D/AmazonFreeRTOSDevice: <-<-<- Writing to characteristic: SAVE_NETWORK  with data: a561624614ae85ef3be96167
2020-08-10 13:35:00.666 20599-21084/App Id W/AmazonFreeRTOSDevice: Ble command failed to be sent OR timeout after 3000ms
2020-08-10 13:35:00.666 20599-21084/AppId D/AmazonFreeRTOSDevice: There's no ble command in the queue.
2020-08-10 13:35:02.764 20599-20619/AppID D/AmazonFreeRTOSDevice: onCharacteristicWrite for: SAVE_NETWORK; status: 133; value: a561624614ae85ef3be96167
2020-08-10 13:35:02.764 20599-20619/AppId E/AmazonFreeRTOSDevice: Unknown characteristic 3113a187-4b9f-4f9a-aa83-c614e11bff02
2020-08-10 13:35:02.764 20599-20619/AppId D/AmazonFreeRTOSDevice: There's no ble command in the queue.
2020-08-10 13:35:02.765 20599-20619/AppID D/BluetoothGatt: onClientConnectionState() - status=8 clientIf=12 device=4C:11:AE:EB:7F:86
2020-08-10 13:35:02.770 20599-20619/AppID I/AmazonFreeRTOSDevice: BLE connection state changed: 8; new state: BLE_DISCONNECTED
2020-08-10 13:35:02.770 20599-20619/AppID I/AmazonFreeRTOSDevice: Disconnected from GATT server.
2020-08-10 13:35:02.770 20599-20619/AppID D/RNAfrmodule: Ble StatusBLE_DISCONNECTED
2020-08-10 13:35:02.771 20599-20619/AppIID D/BluetoothGatt: close()
2020-08-10 13:35:02.775 20599-20692/AppID I/ReactNativeJS: 'afrBleStatus res ', { connectionStatus: 0 }
2020-08-10 13:35:02.792 20599-20619/APPID D/BluetoothGatt: unregisterApp() - mClientIf=12
2020-08-10 13:35:02.822 20599-20599/AppID D/Dialog: mIsSamsungBasicInteraction = false

**Analysis on Other Phone**
it is working on other android phones.

Kindly help us with this issue, as it is impacting our customers.

**Comment by ravibhagavandas** [comment]
Hello,

Thanks for bringing this into our attention. Could you provide following details to debug the issue further:

1. release version/commit ID  of Android SDK
2. release version/commit ID of FreeRTOS
3. board on which the firmware is running
4. If its an ESP32 board, the BLE stack being used (Nimble/Bluedroid).
5. Could you also post the full logs of Android SDK from the start and if possible device side logs?

**Comment by pentair-mywater-residentail** [comment]
Hi,

Please find all the details below:

1. release version/commit ID of Android SDK - **Version 1.0**
2. release version/commit ID of FreeRTOS - **AFR v1.4.7**
3. board on which the firmware is running - **ESP32**
4. If its an ESP32 board, the BLE stack being used (Nimble/Bluedroid). - **Bluedroid**
5. Could you also post the full logs of Android SDK from the start and if possible device side logs? - 

**Android SDK Logs**
[androidlog_AFR.txt](https://github.com/aws/amazon-freertos-ble-android-sdk/files/5085790/androidlog_AFR.txt)

**Device Logs**
[screenlog_S10_DEV_AFR_SSS1.txt](https://github.com/aws/amazon-freertos-ble-android-sdk/files/5085870/screenlog_S10_DEV_AFR_SSS1.txt)

**Comment by ravibhagavandas** [comment]
Hi,

There was a known issue with the older version of bluedroid that,  MTU negotiation between bluedroid stack and Samsung Galaxy S10 device does not occur correctly.

You can read related issue posted on ESP forum here: https://github.com/espressif/esp-idf/issues/4689

We were able to reproduce the same with Bluedroid stack and our Android SDK in this issue: https://github.com/aws/amazon-freertos-ble-android-sdk/issues/15

To confirm if this is the issue could you do a test by writing (with response) a payload of size larger than 23 bytes from android SDK to any characteristic on the board and see if it disconnects ?

The fix for the issue has been merged to ESP IDF release/v3.3 as mentioned in the forum and ESP recommends to use commit IDs `a4144318` and  `ab175f88` from [release/v3.3](https://github.com/espressif/esp-idf/tree/release/v3.3)  branch  for the fix. 

The fix has also been merged to latest Amazon FreeRTOS master branch in this PR: https://github.com/aws/amazon-freertos/pull/2062

**Comment by pentair-mywater-residentail** [comment]
Thanks @ravibhagavandas , we will try this solution and let you know in case we face any issue.

**Comment by pentair-mywater-residentail** [comment]
@ravibhagavandas : Espressif suggested a rebase of the v3.1 ESP-IDF code base. This cannot be done as we are using AFR.
We tried cherry picking the fix from the Espressif branch but there is a library (libbtdm_app.a) which is giving build errors.
The build errors are as below. Could you suggest solution to resolve this.

/code/lib/third_party/mcu_vendor/espressif/esp-idf/components/bt/lib/libbtdm_app.a(ld_fm.o): In function `r_ld_fm_sket_isr':
ld_fm.c:(.iram1.text+0x134): undefined reference to `ld_inq_frm_cbk'
/code/lib/third_party/mcu_vendor/espressif/esp-idf/components/bt/lib/libbtdm_app.a(ld_inq.o):(.iram1.text+0x40): undefined reference to `ld_inq_end'
/code/lib/third_party/mcu_vendor/espressif/esp-idf/components/bt/lib/libbtdm_app.a(ld_inq.o):(.iram1.text+0x44): undefined reference to `ld_inq_sched'
/code/lib/third_party/mcu_vendor/espressif/esp-idf/components/bt/lib/libbtdm_app.a(ld_inq.o): In function `ld_inq_frm_isr_wrapper':
ld_inq.c:(.iram1.text+0x3b3): undefined reference to `ld_inq_end'
ld_inq.c:(.iram1.text+0x3d4): undefined reference to `ld_inq_sched'
/code/lib/third_party/mcu_vendor/espressif/esp-idf/components/bt/lib/libbtdm_app.a(dbg_task.o): In function `hci_vendor_ble_init_adv_flow_control_cmd_handler':
dbg_task.c:(.text+0x104): undefined reference to `dbg_default_state'
/code/lib/third_party/mcu_vendor/espressif/esp-idf/components/bt/lib/libbtdm_app.a(lc_sco.o):(.text+0x0): undefined reference to `lc_sco_env'
collect2: error: ld returned 1 exit status
/code/app/make/../../lib/third_party/mcu_vendor/espressif/esp-idf/make/project.mk:406: recipe for target '/code/app/make/build/afr_app.elf' failed
make: *** [/code/app/make/build/afr_app.elf] Error 1

**Comment by ravibhagavandas** [comment]
Hi,

I am trying to reproduce the issue on Amazon FreeRTOS with  ESP IDF 3.1.

Can you provide information on the baseline AFR commit ID which you are based on ? Release 1.4.7 as mentioned above does not contain the BLE library. Is the esp-idf in the branch ble-beta of Amazon FreeRTOS ( https://github.com/aws/amazon-freertos/tree/feature/ble-beta/lib/third_party/mcu_vendor/espressif/esp-idf ) a good baseline to start?

Also could you point me the commit IDs on v3.1 to cherry-pick as the fix for issue ?

**Comment by pentair-mywater-residentail** [comment]
@ravibhagavandas : We received a Quick fix option from Espressif. A cherry picked v3.1 BT controller's library from espressif was used to build as part of AFR firmware. Testing was done with this firmware but the behavior is observed to be same as earlier.

**Comment by abhidixi11** [comment]
I'm closing this issue, please feel free to open a new one.
