### ISSUE TITLE
PIN Based Bluetooth Connection

### ISSUE THREAD

**Issue by UVohra** [aws/amazon-freertos-ble-android-sdk#50]
I am trying to connect to a Bluetooth device which is restricted with Pin Authentication but cannot see an option to pass that PIN via the Android SDK.

**System info**
Android version: 13

**To Reproduce**
Frequency: No Support
Steps to reproduce the behavior: Connect with Bluetooth device restricted with pin

**Comment by shubnil** [comment]
Hi, Can you elaborate more on this.  We always try to have queries specific to FreeRTOS, so it might be more helpful if you post this queries in other forums like EmbedTLS.

**Comment by kstribrnAmzn** [comment]
From what I can tell, the general flow is something like this:

1. Your peripheral will need to broadcast out it's intent to pair using a pin. This intent to pair is given through an [action](https://developer.android.com/reference/android/content/Intent?hl=en#fields) which in turn will have it's "extra int" field set (aka  [EXTRA_PAIRING_VARIANT](https://developer.android.com/reference/android/bluetooth/BluetoothDevice#EXTRA_PAIRING_VARIANT)) to the [PAIRING_VARIANT_PIN](https://developer.android.com/reference/android/bluetooth/BluetoothDevice#PAIRING_VARIANT_PIN) value which indicates the need to pair with a pin.
2. Your broadcast receiver will receive this, discover the action, and then set the BLE devices own pin with the [setPin](https://developer.android.com/reference/android/bluetooth/BluetoothDevice#setPin(byte[])) method before the BLE object can initiate the connection process.

For some code pointers:
* The Broadcast Receiver looks to be setup [here](https://github.com/aws/amazon-freertos-ble-android-sdk/blob/644a73d42d266ea7e3fc016af520a98e06d20ef5/amazonfreertossdk/src/main/java/software/amazon/freertos/amazonfreertossdk/AmazonFreeRTOSDevice.java#L389-L424)
* The BLE device can be modified to use a pin before connecting [here](https://github.com/aws/amazon-freertos-ble-android-sdk/blob/644a73d42d266ea7e3fc016af520a98e06d20ef5/amazonfreertossdk/src/main/java/software/amazon/freertos/amazonfreertossdk/AmazonFreeRTOSDevice.java#L157-L165)

For reference, I found [this StackOverflow post](https://stackoverflow.com/questions/42677164/ble-peripheral-pairing-pin-on-android) helpful. There is also example code provided with it.
The [BLE 4.2 corespec](https://www.bluetooth.com/specifications/specs/core-specification-4-2/) volume 3, part H, chapter 2.3.5 may also be helpful.

**Comment by mukesh-simform** [comment]
@kstribrnAmzn Thank you for your suggestions here.

As suggested I’ve updated Broadcast Receiver with `ACTION_PAIRING_REQUEST` and added logic there to pass the custom PIN using `setPin` method.

<img width="918" alt="Screenshot 2023-06-06 at 3 01 17 PM" src="https://github.com/aws/amazon-freertos-ble-android-sdk/assets/56827526/70744597-1d35-48de-b5f9-d56848dda11e">


Before that even registered the  `ACTION_PAIRING_REQUEST` receiver. But I’ve observed that `registerBondStateCallback` method never gets triggered in my case and as a result, I’m not able to `setPin`.

<img width="813" alt="Screenshot 2023-06-06 at 3 01 46 PM" src="https://github.com/aws/amazon-freertos-ble-android-sdk/assets/56827526/9fb14d86-20c5-4f90-aea7-7b9181fed0c5">

<img width="930" alt="Screenshot 2023-06-06 at 3 02 25 PM" src="https://github.com/aws/amazon-freertos-ble-android-sdk/assets/56827526/7ecba40a-04dd-418f-b940-214b9cb5e1f3">


Peripheral already broadcasting intent to Pair with PIN and I’m getting a default OS popup to enter the PIN that I don’t want instead I want to pass a custom PIN and even don’t want the user to see that default OS popup 
<img width="329" alt="Screenshot 2023-06-05 at 5 55 57 PM" src="https://github.com/aws/amazon-freertos-ble-android-sdk/assets/56827526/d22a5345-6d20-43ff-8e53-662d881b4327">

Maybe it will require some additional changes. Kindly let me know if that's the case and suggest how can I manage to setPin using this SDK without showing user a default popup

**Comment by kstribrnAmzn** [comment]
Thanks for really diving into this @mukesh-simform! I wonder if entering the pin manually is really needed. [This stack overflow post](https://stackoverflow.com/questions/56626964/how-to-hide-the-pairing-dialog-box-to-programmatically-pair-a-ble-device-on-andr) seems to suggest that the dialog is in error and goes away once the `setPin` call is made. The user found `abortBroadcast();` was a way to remove this dialog. That being said this post is 3 years old so I'm not sure if this was some sort of bug which was patched out.

Overall - I'm not sure the issue here is due to our SDK. There are a number of questions around this various topic posted online and all answers suggest this dialog is a system dialog and cannot be hidden. I would recommend either...

1. Using 'Just Works' pairing. By doing so, there is no pin pop up. You could have the initiating device verify the pin is sent by the requesting device once the connection is established, like is suggested [here](https://lembergsolutions.com/blog/how-secure-ble-communication-standard).
2. Considering an already loaded pin (if you must have the pin) however this will lead to a popup AND is a bad solution if your embedded device has no way of displaying the pin. See [this Bluetooth Blog post](https://www.bluetooth.com/blog/bluetooth-pairing-part-4/) for more.

**Comment by mukesh-simform** [comment]
@AniruddhaKanhere @kstribrnAmzn 
I've managed this with some additional changes in a local copy of SDK and It's working fine on Android

**Comment by AniruddhaKanhere** [comment]
Thank you for replying to us @mukesh-simform.

I shall close this issue now.
